// learning-react/src/components/Pelicula/Pelicula.js
import React, { Component } from "react";

export default class Pelicula extends Component {
  /**
   * PROPERTIES
   */

  // Render method
  render() {
    const { titulo, image } = this.props.pelicula;
    return (
      <div>
        <article id="article-template" className="article-item">
          <div className="image-wrap">
            <img src={image} alt={titulo} />
          </div>
          <h2>{titulo}</h2>
          <span className="date">Hace 5 minutos</span>
          {/* <a href="#">Leer más</a> */}
          <button onClick={this.marcar}>Marcar como favorita</button>
          {/* LIMPIAR FLOATS */}
          <div className="clearfix"></div>
        </article>
      </div>
    );
  }

  /**
   * METHODS
   */
  marcar = () => {
    this.props.marcarFavorita(this.props.pelicula);
  };
}

// learning-angular/src/app/components/peliculas/pelicula/pelicula.component.ts
import { Component, OnInit, Input, Output } from "@angular/core";
import Pelicula from "src/app/models/Pelicula";
import { EventEmitter } from "protractor";

@Component({
  selector: "app-pelicula",
  templateUrl: "./pelicula.component.html",
  styleUrls: ["./pelicula.component.css"]
})
export class PeliculaComponent implements OnInit {
  /**
   * PROPERTIES
   */
  @Input() pelicula: Pelicula;
  @Output() marcarFavorita = new EventEmitter();

  constructor() {}

  ngOnInit() {}

  // Method to pass data (selected movie) from this component to its father.
  pasarFavorita(pelicula) {
    this.marcarFavorita.emit(pelicula);
  }
}

<article class="article-item">
  <div class="image-wrap">
    <img src="{{ pelicula.image }}" alt="{{ pelicula.title }}" />
  </div>
  <h2>{{ pelicula.title }}</h2>
  <span class="date">Hace 5 minutos</span>
  <a href="#">Leer más</a>
  <button (click)="pasarFavorita(pelicula)">Seleccionar como favorita</button>
  <span
    [ngClass]="{
      'year-green': pelicula.year < 3000,
      'year-red': pelicula.year >= 3000
    }"
    >{{ pelicula.year }}</span
  >
  <!-- LIMPIAR FLOATS -->
  <div class="clearfix"></div>
</article>
