// learning-react/src/App.js
import React from "react";
import "./assets/css/App.css";

// Components Imports.
import Header from "./components/Header/Header";
import Slider from "./components/Slider/Slider";
import Sidebar from "./components/Sidebar/Sidebar";
import Footer from "./components/Footer/Footer";
import Peliculas from "./components/Peliculas/Peliculas";

function App() {
  return (
    <div className="App">
      <Header></Header>
      <Slider></Slider>
      <div class="center">
        <Peliculas></Peliculas>
        <Sidebar></Sidebar>
      </div>
      <Footer></Footer>
    </div>
  );
}

export default App;

// learning-vue/src/App.vue
<template>
  <div id="app">
    <Header></Header>
    <Slider></Slider>
    <div class="center">
      <LastArticles></LastArticles>
      <Sidebar></Sidebar>
      <!-- LIMPIAR FLOATS -->
      <div class="clearfix"></div>
    </div>
    <Footer></Footer>
  </div>
</template>

<script>
import Header from "./components/Header";
import Slider from "./components/Slider";
import Sidebar from "./components/Sidebar";
import LastArticles from "./components/LastArticles";
import Footer from "./components/Footer";

export default {
  name: "app",
  components: {
    Header,
    Slider,
    Sidebar,
    LastArticles,
    Footer
  }
};
</script>

<style>
@import "./assets/css/styles.css";
</style>
