// learning-react/src/components/CreateArticle/CreateArticle.js
import React, { Component } from "react";
import axios from "axios";
import { Redirect } from "react-router-dom";
import GLOBAL from "../../Global";
import Sidebar from "../Sidebar/Sidebar";
import "../CreateArticle/CreateArticle.css";

export default class CreateArticle extends Component {
  /**
   * PROPERTIES
   */
  url = GLOBAL.url;

  titleRef = React.createRef();
  contentRef = React.createRef();

  state = {
    article: {},
    status: null,
    selectedFile: null
  };

  // Render method.
  render() {
    if (this.state.status === "success") {
      return <Redirect to="/blog"></Redirect>;
    }
    return (
      <div className="center">
        <section id="content">
          <h1 className="subheader">Crear artículo</h1>
          <form className="mid-form" onSubmit={this.saveArticle}>
            <div className="form-group">
              <label htmlFor="title">Título</label>
              <input
                type="text"
                name="title"
                ref={this.titleRef}
                onChange={this.changeState}
              ></input>
            </div>
            <div className="form-group">
              <label htmlFor="content">Contenido</label>
              <textarea
                type="text"
                name="content"
                ref={this.contentRef}
                onChange={this.changeState}
              ></textarea>
            </div>
            <div className="form-group">
              <label htmlFor="file0">Imagen</label>
              <input
                type="file"
                name="file0"
                onChange={this.fileChange}
              ></input>
            </div>
            <input
              type="submit"
              value="Guardar"
              className="btn btn-success"
            ></input>
          </form>
        </section>
        <Sidebar />
      </div>
    );
  }

  // Method to save an article in the DB.
  saveArticle = event => {
    event.preventDefault();
    // Fill the state with the form values.
    this.changeState();
    // Make an HTTP request to save the article in the DB.
    axios.post(this.url + "save", this.state.article).then(response => {
      if (response.data.article) {
        this.setState({
          article: response.data.article,
          status: "waiting"
        });
        // Uploading the image to the article.
        if (this.state.selectedFile !== null) {
          this.saveImage(response);
        } else {
          this.setState({
            status: "success"
          });
        }
      } else {
        this.setState({
          status: "failed"
        });
      }
    });
  };

  // Method to save the image of an article.
  saveImage = () => {
    // Retrieve the article's ID.
    const ARTICLE_ID = this.state.article._id;
    // Create a Form data and add the file.
    const FORM_DATA = new FormData();
    FORM_DATA.append(
      "file0",
      this.state.selectedFile,
      this.state.selectedFile.name
    );
    // AJAX request.
    axios
      .post(this.url + "upload-image/" + ARTICLE_ID, FORM_DATA)
      .then(response => {
        if (response.data.article) {
          this.setState({
            article: response.data.article,
            status: "success"
          });
        } else {
          this.setState({
            article: response.data.article,
            status: "failed"
          });
        }
      });
  };

  // Method to change the state of the component whenever the "saveArticle" is called.
  changeState = () => {
    this.setState({
      article: {
        title: this.titleRef.current.value,
        content: this.contentRef.current.value
      }
    });
  };

  // Method to
  fileChange = event => {
    this.setState({
      selectedFile: event.target.files[0]
    });
  };
}

// learning-vue/src/components/CreateArticle.vue
<template>
  <div>
    <div class="center">
      <section id="content">
        <h1 class="subheader">Crea tu propio artículo</h1>
        <!-- FORM -->
        <form class="mid-form" @submit.prevent="submit">
          <div class="form-group">
            <label for="title">Título</label>
            <input type="text" name="title" v-model="article.title" />
            <div v-if="submitted && !$v.article.title.required">Introduce un título</div>
          </div>
          <div class="form-group">
            <label for="content">Contenido</label>
            <textarea type="text" name="content" v-model="article.content" />
            <div
              v-if="submitted && !$v.article.content.required"
            >Introduce contenido para el artículo</div>
          </div>
          <div class="form-group">
            <label for="image">Imagen</label>
            <input type="file" name="file0" id="file" ref="file" @change="fileChange" />
          </div>
          <!-- LIMPIAR FLOATS -->
          <div class="clearfix"></div>
          <input type="submit" value="Guardar" class="btn btn-success" />
        </form>
      </section>
      <Sidebar></Sidebar>
      <!-- LIMPIAR FLOATS -->
      <div class="clearfix"></div>
    </div>
  </div>
</template>

<script>
import Sidebar from "./Sidebar";
import ARTICLE from "../models/article";
import GLOBAL from "../Global";
import axios from "axios";
import { required } from "vuelidate/lib/validators";

export default {
  name: "CreateArticle",
  components: {
    Sidebar
  },
  data() {
    return {
      article: ARTICLE,
      file: null,
      url: GLOBAL.url,
      submitted: false
    };
  },
  methods: {
    // Method to submit the form.
    submit() {
      this.submitted = true;
      // The validations have been touched...
      this.$v.$touch();
      // If the form is invalid...
      if (this.$v.$invalid) {
        // Fails silently.
        return false;
      } else {
        // Save the data submitted by the form.
        this.saveData();
      }
    },
    // Method to save any article created by the user.
    saveData() {
      axios.post(this.url + "save", this.article).then(response => {
        if (response.data.status === "success") {
          this.saveArticle(response);
        }
      });
    },
    // In case the response.data.status is === "success".
    saveArticle(response) {
      // Uploading the image file in case has content.
      if (this.file !== null && this.file !== undefined && this.file !== "") {
        // Create a FormData instance.
        const FORM_DATA = new FormData();
        // /**
        //  * Append to it the key "file0" with the image value
        //  * (this.file.name) and the full content  of the file
        //  */
        FORM_DATA.append("file0", this.file, this.file.name);
        axios
          .post(
            this.url + "upload-image/" + response.data.article._id,
            FORM_DATA
          )
          .then(response => {
            if (response.data.article) {
              // Redirection.
              this.$router.push("/blog");
            }
          });
      } else {
        // Redirection.
        this.$router.push("/blog");
      }
    },
    // Linking the introduced image by the user to the article.
    fileChange() {
      this.file = this.$refs.file.files[0];
    }
  },
  validations: {
    article: {
      title: { required },
      content: { required }
    }
  }
};
</script>

<style scoped>
#file {
  border: none;
}
</style>
