// learning-react/src/components/Error/Error.js
import React, { Component } from "react";

export default class Error extends Component {
  render() {
    return (
      <div>
        <section id="content">
          <h2 className="subheader">Página no encontrada</h2>
          <p>La página a la que intentas acceder no existe en la web</p>
        </section>
      </div>
    );
  }
}

// learning-vue/src/components/ErrorComponent.vue
<template>
  <div>
    <section id="content">
      <h2 class="subheader">Página no encontrada</h2>
      <h3>La página que bsucas no existe. Inténtalo más tarde</h3>
    </section>
    <!-- LIMPIAR FLOATS -->
      <div class="clearfix"></div>
  </div>
</template>

<script>
export default {
  name: "ErrorComponent"
};
</script>

<style scoped>
</style>
