// learning-angular/src/app/components/peliculas/peliculas.component.ts
import { Component, OnInit, DoCheck, OnDestroy } from "@angular/core";

@Component({
  selector: "app-peliculas",
  templateUrl: "./peliculas.component.html",
  styleUrls: ["./peliculas.component.css"]
})
export class PeliculasComponent implements OnInit, DoCheck, OnDestroy {
  /**
   * PROPERTIES
   */
  peliculas: Array<any>;

  // Constructor
  constructor() {
    this.peliculas = [
      {
        title: "Batman vs Superman",
        image:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6tNuPs5PSfZmfuZgHqnbnXvaKVC7tyZ53YIW0K8BwMUJh8QWq&s",
        year: 2019
      },
      {
        title: "Gran Torino",
        image:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS--DQBBY_3MqtNHYlJOe3C3jPK4mM3UrZM-PfpNYSh9ml5pCS5&s",
        year: 2065
      },
      {
        title: "El señor de los anillos",
        image:
          "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0gOGi-dQQ5xaBpdS0a8YyMrnMUslwsFTtq4QDJ4REyPLRp64DjQ&s",
        year: 3000
      }
    ];
    console.log("Constructor lanzado");
  }

  /**
   * COMPONENT LIFECYCLE -> HOOKS
   */

  // Whenever the component is built...
  ngOnInit() {
    console.log("Componente iniciado");
  }

  // Whenever the component is updated...
  ngDoCheck() {
    console.log("DoCheck lanzado");
  }

  // Whenever the component is destroyed...
  ngOnDestroy() {
    console.log("OnDestroy lanzado");
  }
}

<h1 class="subheader">
  Listado de películas
</h1>
<div *ngIf="peliculas">
  <article
    *ngFor="let pelicula of peliculas; let index = index"
    class="article-item"
  >
    <div class="image-wrap">
      <img src="{{ pelicula.image }}" alt="{{ pelicula.title }}" />
    </div>
    <h2>{{ pelicula.title }}</h2>
    <span class="date">Hace 5 minutos</span>
    <a href="#">Leer más</a>
    <span
      [ngClass]="{
        'year-green': pelicula.year < 3000,
        'year-red': pelicula.year >= 3000
      }"
      >{{ pelicula.year }}</span
    >
    <!-- LIMPIAR FLOATS -->
    <div class="clearfix"></div>
  </article>
</div>

// learning-vue/src/components/Peliculas.vue
<template>
  <div>
    <section id="content">
      <h2 class="subheader">Películas</h2>
      <!-- LISTADO PELÍCULAS -->
      <div id="articles">
        <article class="article-item" v-for="pelicula in peliculas" :key="pelicula">
          <div class="image-wrap">
            <img :src="pelicula.image" :alt="pelicula.title" :title="pelicula.title" />
          </div>
          <h2>{{pelicula.title}}</h2>
          <span class="date">{{pelicula.year}}</span>
          <a href="#">Leer más</a>

          <!-- LIMPIAR FLOATS -->
          <div class="clearfix"></div>
        </article>
      </div>
    </section>
  </div>
</template>

<script>
export default {
  name: "Peliculas",
  data() {
    return {
      peliculas: [
        {
          title: "Batman vs Superman",
          year: 2017,
          image:
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6tNuPs5PSfZmfuZgHqnbnXvaKVC7tyZ53YIW0K8BwMUJh8QWq&s"
        },
        {
          title: "Gran Torino",
          year: 2015,
          image:
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS--DQBBY_3MqtNHYlJOe3C3jPK4mM3UrZM-PfpNYSh9ml5pCS5&s"
        },
        {
          title: "El señor de los anillos",
          year: 2003,
          image:
            "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0gOGi-dQQ5xaBpdS0a8YyMrnMUslwsFTtq4QDJ4REyPLRp64DjQ&s"
        }
      ]
    };
  }
};
</script>

<style scoped>
</style>
