// learning-react/src/components/Pelicula/Pelicula.js
import React, { Component } from "react";

export default class Pelicula extends Component {
  /**
   * PROPERTIES
   */

  // Render method
  render() {
    const { titulo, image } = this.props.pelicula;
    return (
      <div>
        <article id="article-template" className="article-item">
          <div className="image-wrap">
            <img src={image} alt={titulo} />
          </div>
          <h2>{titulo}</h2>
          <span className="date">Hace 5 minutos</span>
          {/* <a href="#">Leer más</a> */}
          <button onClick={this.marcar}>Marcar como favorita</button>
          {/* LIMPIAR FLOATS */}
          <div className="clearfix"></div>
        </article>
      </div>
    );
  }

  /**
   * METHODS
   */
  marcar = () => {
    this.props.marcarFavorita(this.props.pelicula);
  };
}

// learning-vue/src/components/Pelicula.vue
<template>
  <div>
    <article class="article-item">
      <div class="image-wrap">
        <img :src="pelicula.image" :alt="pelicula.title" :title="pelicula.title" />
      </div>
      <h3>{{pelicula.title}}</h3>
      <span
        class="date"
        :class="{
              yeargreen: pelicula.year >= 2015,
              yearred: pelicula.year < 2015
          }"
      >{{pelicula.year}}</span>
      <a href="#">Leer más</a>

      <input type="button" value="Marcar como favorita" @click="pasarFavoritaAlPadre(pelicula)" />

      <!-- LIMPIAR FLOATS -->
      <div class="clearfix"></div>
    </article>
  </div>
</template>

<script>
export default {
  name: "Pelicula",
  props: ["pelicula"],
  methods: {
    pasarFavoritaAlPadre(pelicula) {
      this.$emit("favorita", pelicula);
    }
  }
};
</script>

<style scoped>
</style>
